const defaultAnimation = {
  duration: 1,
  delay: 0,
  timingFunction: "linear",
  direction: "normal",
  count: 1,
  mode: "both",
  playState: "running",
};
/**
 * @param type 1 进入 2 强调 3 退出
 */
export const animationList = [
  {
    id: 1,
    type: 1,
    x: "360px",
    y: "0px",
    actionY: "200px",
    isMoveIn: false,
    name: "淡入",
    animation: {
      id: 1,
      title: "淡入",
      name: "fadeIn",
      ...defaultAnimation,
    },
  },
  {
    id: 2,
    type: 1,
    x: "120px",
    y: "-80px",
    actionY: "-560px",
    isMoveIn: false,
    name: "向右移入",
    animation: {
      id: 2,
      title: "向右移入",
      name: "fadeInLeft",
      ...defaultAnimation,
    },
  },
  {
    id: 3,
    type: 1,
    x: "160px",
    y: "-120px",
    actionY: "-600px",
    isMoveIn: false,
    name: "向左移入",
    animation: {
      id: 3,
      title: "向左移入",
      name: "fadeInRight",
      ...defaultAnimation,
    },
  },
  {
    id: 4,
    type: 1,
    x: "40px",
    y: "0px",
    actionY: "-480px",
    isMoveIn: false,
    name: "向上移入",
    animation: {
      id: 4,
      title: "向上移入",
      name: "fadeInUp",
      ...defaultAnimation,
    },
  },
  {
    id: 5,
    type: 2,
    x: "360px",
    y: "-200px",
    actionY: "-680px",
    isMoveIn: false,
    name: "摇摆",
    animation: {
      id: 5,
      title: "摇摆",
      name: "wobble",
      ...defaultAnimation,
    },
  },
  {
    id: 6,
    type: 3,
    x: "360px",
    y: "-240px",
    actionY: "-720px",
    isMoveIn: false,
    name: "淡出",
    animation: {
      id: 6,
      title: "淡出",
      name: "fadeOut",
      ...defaultAnimation,
    },
  },
];
