const defaultAnimation = {
  duration: 1,
  delay: 0,
  timingFunction: "linear",
  direction: "normal",
  count: 1,
  mode: "both",
  playState: "running",
};
/**
 * @param type 1 进入 2 强调 3 退出
 */
export const entry = [
  {
    id: 1,
    type: 1,
    name: "淡入",
    x: "360px",
    y: "0px",
    isMoveIn: false,
    actionY: "200px",
    animation: { id: 1, title: "淡入", name: "fadeIn", ...defaultAnimation },
  },
  {
    id: 2,
    type: 1,
    name: "向右移入",
    x: "120px",
    y: "-80px",
    isMoveIn: false,

    actionY: "-560px",
    animation: {
      id: 2,
      title: "向右移入",
      name: "fadeInLeft",
      ...defaultAnimation,
    },
  },
  {
    id: 3,
    type: 1,
    name: "向左移入",
    x: "160px",
    y: "-120px",
    isMoveIn: false,

    actionY: "-600px",
    animation: {
      id: 3,
      title: "向左移入",
      name: "fadeInRight",
      ...defaultAnimation,
    },
  },
  {
    id: 4,
    type: 1,
    name: "向上移入",
    x: "40px",
    y: "0px",
    isMoveIn: false,

    actionY: "-480px",
    animation: {
      id: 4,
      title: "向上移入",
      name: "fadeInUp",
      ...defaultAnimation,
    },
  },
  {
    id: 5,
    type: 1,
    name: "向下移入",
    x: "160px",
    y: "-40px",
    isMoveIn: false,

    actionY: "-520px",
    animation: {
      id: 5,
      title: "向下移入",
      name: "fadeInDown",
      ...defaultAnimation,
    },
  },
  {
    id: 6,
    type: 1,
    name: "翻转进入",
    x: "200px",
    y: "0px",
    isMoveIn: false,

    actionY: "-480px",
    animation: {
      id: 6,
      title: "翻转进入",
      name: "flipInY",
      ...defaultAnimation,
    },
  },
  {
    id: 7,
    type: 1,
    name: "向右弹入",
    x: "240px",
    y: "-80px",
    isMoveIn: false,

    actionY: "-560px",
    animation: {
      id: 7,
      title: "向右弹入",
      name: "bounceInLeft",
      ...defaultAnimation,
    },
  },
  {
    id: 8,
    type: 1,
    name: "向左弹入",
    x: "280px",
    y: "-120px",
    isMoveIn: false,

    actionY: "-600px",
    animation: {
      id: 8,
      title: "向左弹入",
      name: "bounceInRight",
      ...defaultAnimation,
    },
  },
  {
    id: 9,
    type: 1,
    name: "向上弹入",
    x: "160px",
    y: "0px",
    isMoveIn: false,

    actionY: "-480px",
    animation: {
      id: 9,
      title: "向上弹入",
      name: "bounceInUp",
      ...defaultAnimation,
    },
  },
  {
    id: 10,
    type: 1,
    name: "向下弹入",
    x: "280px",
    y: "-40px",
    isMoveIn: false,

    actionY: "-520px",
    animation: {
      id: 10,
      title: "向下弹入",
      name: "bounceInDown",
      ...defaultAnimation,
    },
  },
  {
    id: 11,
    type: 1,
    name: "翻开进入",
    x: "320px",
    y: "-240px",
    isMoveIn: false,

    actionY: "-720px",
    animation: {
      id: 11,
      title: "翻开进入",
      name: "flipInX",
      ...defaultAnimation,
    },
  },
  {
    id: 12,
    type: 1,
    name: "向右翻滚",
    x: "200px",
    y: "-80px",
    isMoveIn: false,

    actionY: "-560px",
    animation: {
      id: 12,
      title: "向右翻滚",
      name: "rollInRight",
      ...defaultAnimation,
    },
  },
  {
    id: 13,
    type: 1,
    name: "向左翻滚",
    x: "240px",
    y: "-120px",
    isMoveIn: false,

    actionY: "-600px",
    animation: {
      id: 13,
      title: "向左翻滚",
      name: "rollInLeft",
      ...defaultAnimation,
    },
  },
  {
    id: 14,
    type: 1,
    name: "向上翻滚",
    x: "120px",
    y: "0px",
    isMoveIn: false,

    actionY: "-480px",
    animation: {
      id: 14,
      title: "向上翻滚",
      name: "rollInUp",
      ...defaultAnimation,
    },
  },
  {
    id: 15,
    type: 1,
    name: "向下翻滚",
    x: "240px",
    y: "-40px",
    isMoveIn: false,

    actionY: "-520px",
    animation: {
      id: 15,
      title: "向下翻滚",
      name: "rollInDown",
      ...defaultAnimation,
    },
  },
  {
    id: 16,
    type: 1,
    name: "中心弹入",
    x: "280px",
    y: "-160px",
    isMoveIn: false,

    actionY: "-640px",
    animation: {
      id: 16,
      title: "中心弹入",
      name: "bounceIn",
      ...defaultAnimation,
    },
  },
  {
    id: 17,
    type: 1,
    name: "光速向右",
    x: "320px",
    y: "-80px",
    isMoveIn: false,

    actionY: "-560px",
    animation: {
      id: 17,
      title: "光速向右",
      name: "lightSpeedInRight",
      ...defaultAnimation,
    },
  },
  {
    id: 18,
    type: 1,
    name: "光速向左",
    x: "360px",
    y: "-120px",
    isMoveIn: false,

    actionY: "-600px",
    animation: {
      id: 18,
      title: "光速向左",
      name: "lightSpeedInLeft",
      ...defaultAnimation,
    },
  },
  {
    id: 19,
    type: 1,
    name: "光速向上",
    x: "280px",
    y: "0px",
    isMoveIn: false,

    actionY: "-480px",
    animation: {
      id: 19,
      title: "光速向上",
      name: "lightSpeedInUp",
      ...defaultAnimation,
    },
  },
  {
    id: 20,
    type: 1,
    name: "光速向下",
    x: "360px",
    y: "-40px",
    isMoveIn: false,

    actionY: "-520px",
    animation: {
      id: 20,
      title: "光速向下",
      name: "lightSpeedInDown",
      ...defaultAnimation,
    },
  },
  {
    id: 21,
    type: 1,
    name: "中心放大",
    x: "280px",
    y: "-240px",
    isMoveIn: false,

    actionY: "-720px",
    animation: {
      id: 21,
      title: "中心放大",
      name: "zoomIn",
      ...defaultAnimation,
    },
  },
  {
    id: 22,
    type: 1,
    name: "魔幻向右",
    x: "280px",
    y: "-80px",
    isMoveIn: false,

    actionY: "-560px",
    animation: {
      id: 22,
      title: "魔幻向右",
      name: "twisterInDownRight",
      ...defaultAnimation,
    },
  },
  {
    id: 23,
    type: 1,
    name: "魔幻向左",
    x: "320px",
    y: "-120px",
    isMoveIn: false,

    actionY: "-600px",
    animation: {
      id: 23,
      title: "魔幻向左",
      name: "twisterInDownLeft",
      ...defaultAnimation,
    },
  },
  {
    id: 24,
    type: 1,
    name: "魔幻向上",
    x: "240px",
    y: "0px",
    isMoveIn: false,

    actionY: "-480px",
    animation: {
      id: 24,
      title: "魔幻向上",
      name: "twisterInDownUp",
      ...defaultAnimation,
    },
  },
  {
    id: 25,
    type: 1,
    name: "魔幻向下",
    x: "320px",
    y: "-40px",
    isMoveIn: false,

    actionY: "-520px",
    animation: {
      id: 25,
      title: "魔幻向下",
      name: "twisterInDownDown",
      ...defaultAnimation,
    },
  },
  {
    id: 26,
    type: 1,
    name: "缩小进入",
    x: "400px",
    y: "-80px",
    isMoveIn: false,

    actionY: "-560px",
    animation: {
      id: 26,
      title: "缩小进入",
      name: "puffIn",
      ...defaultAnimation,
    },
  },
  {
    id: 27,
    type: 1,
    name: "向左旋转",
    x: "160px",
    y: "-80px",
    isMoveIn: false,

    actionY: "-560px",
    animation: {
      id: 27,
      title: "向左旋转",
      name: "twisterInUpLeft",
      ...defaultAnimation,
    },
  },
  {
    id: 28,
    type: 1,
    name: "向右旋转",
    x: "200px",
    y: "-120px",
    isMoveIn: false,

    actionY: "-600px",
    animation: {
      id: 28,
      title: "向右旋转",
      name: "twisterInUpRight",
      ...defaultAnimation,
    },
  },
  {
    id: 29,
    type: 1,
    name: "向上旋转",
    x: "80px",
    y: "0px",
    isMoveIn: false,

    actionY: "-480px",
    animation: {
      id: 29,
      title: "向上旋转",
      name: "twisterInUpUp",
      ...defaultAnimation,
    },
  },
  {
    id: 30,
    type: 1,
    name: "向下旋转",
    x: "200px",
    y: "-40px",
    isMoveIn: false,

    actionY: "-520px",
    animation: {
      id: 30,
      title: "向下旋转",
      name: "twisterInUpDown",
      ...defaultAnimation,
    },
  },
];

const emphasize = [
  {
    id: 31,
    type: 2,
    name: "摇摆",
    x: "360px",
    y: "-200px",
    isMoveIn: false,
    animation: {
      id: 31,
      title: "摇摆",
      ...defaultAnimation,
      name: "wobble",
    },
    actionY: "-680px",
  },
  {
    id: 32,
    type: 2,
    name: "抖动",
    x: "360px",
    y: "-160px",
    isMoveIn: false,
    animation: {
      id: 32,
      title: "抖动",
      ...defaultAnimation,
      name: "rubberBand",
    },
    actionY: "-640px",
  },
  {
    id: 33,
    type: 2,
    name: "旋转",
    x: "400px",
    y: "-200px",
    isMoveIn: false,
    animation: {
      id: 33,
      title: "旋转",
      ...defaultAnimation,
      name: "rotateIn",
    },
    actionY: "-680px",
  },
  {
    id: 34,
    type: 2,
    name: "翻转",
    x: "200px",
    y: "0px",
    isMoveIn: false,
    animation: {
      id: 34,
      title: "翻转",
      ...defaultAnimation,
      name: "flip",
    },
    actionY: "-480px",
  },
  {
    id: 35,
    type: 2,
    name: "悬摆",
    x: "80px",
    y: "-160px",
    isMoveIn: false,
    animation: {
      id: 35,
      title: "悬摆",
      ...defaultAnimation,
      name: "swing",
    },
    actionY: "-640px",
  },
  {
    id: 36,
    type: 2,
    name: "闪烁",
    x: "240px",
    y: "-160px",
    isMoveIn: false,
    animation: {
      id: 36,
      title: "闪烁",
      ...defaultAnimation,
      name: "flash",
    },
    actionY: "-640px",
  },
  {
    id: 37,
    type: 2,
    name: "下滑",
    x: "160px",
    y: "-160px",
    isMoveIn: false,
    animation: {
      id: 37,
      title: "下滑",
      ...defaultAnimation,
      name: "slideDown",
    },
    actionY: "-640px",
  },
  {
    id: 38,
    type: 2,
    name: "上滑",
    x: "200px",
    y: "-160px",
    isMoveIn: false,
    animation: {
      id: 38,
      title: "上滑",
      ...defaultAnimation,
      name: "slideUp",
    },
    actionY: "-640px",
  },
  {
    id: 39,
    type: 2,
    name: "放大抖动",
    x: "280px",
    y: "-160px",
    isMoveIn: false,
    animation: {
      id: 39,
      title: "放大抖动",
      ...defaultAnimation,
      name: "tada",
    },
    actionY: "-639px",
  },
  {
    id: 40,
    type: 2,
    name: "倾斜摆动",
    x: "120px",
    y: "-160px",
    isMoveIn: false,
    animation: {
      id: 40,
      title: "倾斜摆动",
      ...defaultAnimation,
      name: "jello",
    },
    actionY: "-640px",
  },
];

const quit = [
  {
    id: 41,
    type: 3,
    name: "淡出",
    x: "360px",
    y: "-240px",
    isMoveIn: false,
    animation: {
      id: 41,
      title: "淡出",
      ...defaultAnimation,
      name: "fadeOut",
    },
    actionY: "-720px",
  },
  {
    id: 42,
    type: 3,
    name: "向右移出",
    x: "280px",
    y: "-320px",
    isMoveIn: false,
    animation: {
      id: 42,
      title: "向右移出",
      ...defaultAnimation,
      name: "fadeOutRight",
    },
    actionY: "-800px",
  },
  {
    id: 43,
    type: 3,
    name: "向左移出",
    x: "280px",
    y: "-360px",
    isMoveIn: false,
    animation: {
      id: 43,
      title: "向左移出",
      ...defaultAnimation,
      name: "fadeOutLeft",
    },
    actionY: "-840px",
  },
  {
    id: 44,
    type: 3,
    name: "向上移出",
    x: "120px",
    y: "-240px",
    isMoveIn: false,
    animation: {
      id: 44,
      title: "向上移出",
      ...defaultAnimation,
      name: "fadeOutUp",
    },
    actionY: "-720px",
  },
  {
    id: 45,
    type: 3,
    name: "向下移出",
    x: "160px",
    y: "-280px",
    isMoveIn: false,
    animation: {
      id: 45,
      title: "向下移出",
      ...defaultAnimation,
      name: "fadeOutDown",
    },
    actionY: "-760px",
  },
  {
    id: 46,
    type: 3,
    name: "向右弹出",
    x: "360px",
    y: "-320px",
    isMoveIn: false,
    animation: {
      id: 46,
      title: "向右弹出",
      ...defaultAnimation,
      name: "bounceOutRight",
    },
    actionY: "-800px",
  },
  {
    id: 47,
    type: 3,
    name: "向左弹出",
    x: "360px",
    y: "-360px",
    isMoveIn: false,
    animation: {
      id: 47,
      title: "向左弹出",
      ...defaultAnimation,
      name: "bounceOutLeft",
    },
    actionY: "-840px",
  },
  {
    id: 48,
    type: 3,
    name: "向上弹出",
    x: "200px",
    y: "-240px",
    isMoveIn: false,
    animation: {
      id: 48,
      title: "向上弹出",
      ...defaultAnimation,
      name: "bounceOutUp",
    },
    actionY: "-720px",
  },
  {
    id: 49,
    type: 3,
    name: "向下弹出",
    x: "240px",
    y: "-280px",
    isMoveIn: false,
    animation: {
      id: 49,
      title: "向下弹出",
      ...defaultAnimation,
      name: "bounceOutDown",
    },
    actionY: "-760px",
  },
  {
    id: 50,
    type: 3,
    name: "翻转消失",
    x: "200px",
    y: "-400px",
    isMoveIn: false,
    animation: {
      id: 50,
      title: "翻转消失",
      ...defaultAnimation,
      name: "flipOutY",
    },
    actionY: "-880px",
  },
  {
    id: 51,
    type: 3,
    name: "中心消失",
    x: "320px",
    y: "-280px",
    isMoveIn: false,
    animation: {
      id: 51,
      title: "中心消失",
      ...defaultAnimation,
      name: "bounceOut",
    },
    actionY: "-760px",
  },
  {
    id: 52,
    type: 3,
    name: "中心缩小",
    x: "400px",
    y: "-80px",
    isMoveIn: false,
    animation: {
      id: 52,
      title: "中心缩小",
      ...defaultAnimation,
      name: "zoomOut",
    },
    actionY: "-560px",
  },
  {
    id: 53,
    type: 3,
    name: "向右翻滚",
    x: "320px",
    y: "-320px",
    isMoveIn: false,
    animation: {
      id: 53,
      title: "向右翻滚",
      ...defaultAnimation,
      name: "rollOutRight",
    },
    actionY: "-800px",
  },
  {
    id: 54,
    type: 3,
    name: "向左翻滚",
    x: "320px",
    y: "-360px",
    isMoveIn: false,
    animation: {
      id: 54,
      title: "向左翻滚",
      ...defaultAnimation,
      name: "rollOutLeft",
    },
    actionY: "-840px",
  },
  {
    id: 55,
    type: 3,
    name: "向上翻滚",
    x: "160px",
    y: "-240px",
    isMoveIn: false,
    animation: {
      id: 55,
      title: "向上翻滚",
      ...defaultAnimation,
      name: "rollOutUp",
    },
    actionY: "-720px",
  },
  {
    id: 56,
    type: 3,
    name: "向下翻滚",
    x: "200px",
    y: "-280px",
    isMoveIn: false,
    animation: {
      id: 56,
      title: "向下翻滚",
      ...defaultAnimation,
      name: "rollOutDown",
    },
    actionY: "-760px",
  },
  {
    id: 57,
    type: 3,
    name: "翻开消失",
    x: "320px",
    y: "-240px",
    isMoveIn: false,
    animation: {
      id: 57,
      title: "翻开消失",
      ...defaultAnimation,
      name: "flipOutX",
    },
    actionY: "-720px",
  },
  {
    id: 58,
    type: 3,
    name: "光速向右",
    x: "400px",
    y: "-320px",
    isMoveIn: false,
    animation: {
      id: 58,
      title: "光速向右",
      ...defaultAnimation,
      name: "lightSpeedOutRight",
    },
    actionY: "-800px",
  },
  {
    id: 59,
    type: 3,
    name: "光速向左",
    x: "400px",
    y: "-360px",
    isMoveIn: false,
    animation: {
      id: 59,
      title: "光速向左",
      ...defaultAnimation,
      name: "lightSpeedOutLeft",
    },
    actionY: "-840px",
  },
  {
    id: 60,
    type: 3,
    name: "光速向上",
    x: "240px",
    y: "-240px",
    isMoveIn: false,
    animation: {
      id: 60,
      title: "光速向上",
      ...defaultAnimation,
      name: "lightSpeedOutUp",
    },
    actionY: "-720px",
  },
  {
    id: 61,
    type: 3,
    name: "光速向下",
    x: "280px",
    y: "-280px",
    isMoveIn: false,
    animation: {
      id: 61,
      title: "光速向下",
      ...defaultAnimation,
      name: "lightSpeedOutDown",
    },
    actionY: "-760px",
  },
  {
    id: 62,
    type: 3,
    name: "放大退出",
    x: "400px",
    y: "-120px",
    isMoveIn: false,
    animation: {
      id: 62,
      title: "放大退出",
      ...defaultAnimation,
      name: "puffOut",
    },
    actionY: "-600px",
  },
  {
    id: 63,
    type: 3,
    name: "向右脱落",
    x: "400px",
    y: "-240px",
    isMoveIn: false,
    animation: {
      id: 63,
      title: "向右脱落",
      ...defaultAnimation,
      name: "hingeRight",
    },
    actionY: "-720px",
  },
  {
    id: 64,
    type: 3,
    name: "向左脱落",
    x: "400px",
    y: "-280px",
    isMoveIn: false,
    animation: {
      id: 64,
      title: "向左脱落",
      ...defaultAnimation,
      name: "hingeLeft",
    },
    actionY: "-760px",
  },
];

export const animationList = [...entry, ...emphasize, ...quit];
// [

// {
//   id: 5,
//   type: 1,
//   x: "160px",
//   y: "-40px",
//   actionY: "-520px",
//   isMoveIn: false,  actionY: "200px",
//   name: "向下移入",
//   animation: {
//     id: 5,
//     title: "向下移入",
//     name: "fadeInDown",
//     ,
//   },
// },
// {
//   id: 6,
//   type: 1,
//   x: "40px",
//   y: "0px",
//   actionY: "-480px",
//   isMoveIn: false,  actionY: "200px",
//   name: "翻转进入",
//   animation: {
//     id: 6,
//     title: "翻转进入",
//     name: "flipInY",
//     ,
//   },
// },
// {
//   id: 5,
//   type: 2,
//   x: "360px",
//   y: "-200px",
//   actionY: "-680px",
//   isMoveIn: false, actionY: "200px",
//   name: "摇摆",
//   animation: {
//     id: 5,
//     title: "摇摆",
//     name: "wobble",
//     ,
//   },
// },
// {
//   id: 6,
//   type: 3,
//   x: "360px",
//   y: "-240px",
//   actionY: "-720px",
//   isMoveIn: false,
//   name: "淡出",
//   animation: {
//     id: 6,
//     title: "淡出",
//     name: "fadeOut",
//     ,
//   },
// },
// ];
