export const jsonPage = {
  page: 1,
  style: {
    backgroundColor: "transparent",
    height: 0,
  },
  componentList: [],
};

export const jsonText = {
  type: "1",
  isMoving: false,
  text: "",
  style: {
    width: "150px",
    height: "31px",
    fontSize: "14px",
    color: "#000",
    borderWidth: "0px",
    borderStyle: "none",
    borderColor: "#000",
    textAlign: "left",
    padding: "5px",
    borderRadius: "0px",
    opacity: 1,
    boxSizing: "border-box",
    transform: "rotate(0deg)",
    zIndex: 2,
    position: "absolute",
    left: 0,
    top: 220,
    backgroundColor: "transparent",
  },
  alternateLeft: 0,
  alternateTop: 220,
  animation: [
    {
      id: 1,
      title: "淡入",
      name: "fadeIn",
      duration: 1,
      delay: 0,
      timingFunction: "linear",
      direction: "normal",
      count: 1,
      mode: "both",
      playState: "running",
    },
  ],
  event: [],
};
